# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(892, 696)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 10, 871, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 871, 531))
        self.textBrowser.setObjectName("textBrowser")
        self.startScanButton = QtWidgets.QPushButton(Dialog)
        self.startScanButton.setGeometry(QtCore.QRect(760, 630, 121, 51))
        self.startScanButton.setObjectName("startScanButton")
        self.selectDirButton = QtWidgets.QPushButton(Dialog)
        self.selectDirButton.setGeometry(QtCore.QRect(10, 630, 131, 51))
        self.selectDirButton.setObjectName("selectDirButton")
        self.selectFileButton = QtWidgets.QPushButton(Dialog)
        self.selectFileButton.setGeometry(QtCore.QRect(160, 630, 131, 51))
        self.selectFileButton.setObjectName("selectFileButton")
        self.scanFilePrompt = QtWidgets.QTextBrowser(Dialog)
        self.scanFilePrompt.setGeometry(QtCore.QRect(300, 630, 451, 51))
        self.scanFilePrompt.setObjectName("scanFilePrompt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.startScanButton.setText(_translate("Dialog", "開始掃描"))
        self.selectDirButton.setText(_translate("Dialog", "選取資料夾"))
        self.selectFileButton.setText(_translate("Dialog", "選取檔案"))
